name: LeakGuard CodeGate Analyzer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  leakguard:
    name: LeakGuard CodeGate Analyzer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: LeakGuard CodeGate Analyzer
        uses: vanshpatil16/VH26-DOMINATORS-5.0@v1.0.0
        with:
          targets: .
          changed-only: false
          base: origin/main
          ensemble: true
